name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Build
      run: make build
    - name: Test
      run: make test
